apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME} # Use the DEPLOYMENT_NAME environment variable
spec:
  replicas: ${REPLICA_COUNT} # Use the REPLICA_COUNT environment variable
  selector:
    matchLabels:
      app: ${APP_NAME} # Use the APP_NAME environment variable
  template:
    metadata:
      labels:
        app: ${APP_NAME} # Use the APP_NAME environment variable
    spec:
      containers:
        - name: ${CONTAINER_NAME} # Use the CONTAINER_NAME environment variable
          image: ${IMAGE_NAME} # Use the IMAGE_NAME environment variable
          ports:
            - containerPort: ${CONTAINER_PORT} # Use the CONTAINER_PORT environment variable
