apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: INGRESS_NAME
  namespace: K8S_NAMESPACE
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/ssl-passthrough: 'false'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - FINAL_SUBDOMAIN.FINAL_DOMAIN
      secretName: tlssecrets
  rules:
    - host: www.FINAL_SUBDOMAIN.FINAL_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ram-nginx-auto-DEPLOYMENT_MODE
                port:
                  number: 80
