apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.imageName }}
