apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "DOMAIN_NAMES"
  namespace: {{k8s_namespace|mandatory}}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/ssl-passthrough: 'false'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - HOST_NAME.ram-dev1.dev.cld.marriott.DOMAIN_NAME
      secretName: tlssecrets
  rules:
    - host: HOST_NAME.ram-dev1.dev.cld.marriott.DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ram-nginx-auto-mi-microservice
                port:
                  number: {{app_port|mandatory}}
